name: SIMPLE CI WORKFLOW

on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [18.x, 20.x, 22.5.0]

    steps: 

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache node modules
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{runner.os}}-node-${{matrix.node-version}}-${{ hashFiles('package-lock.json')}}
          restore-key: | 
              ${{runner.os}}-node-${{matrix.node-version}}

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Generate Coverage Report
        if: success()
        run: npm run converage


      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with: 
          name: test-results
          path: test-results/
        
